<main role="main" class="flex-shrink-0">
    <div class="container">
        <form class="form-signin">
            <img class="mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
            <h1 class="h3 mb-3 font-weight-normal">Пожалуйста, войдите в свой аккаут</h1>
            <label for="inputEmail" class="sr-only">Адрес электронной почты</label>
            <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
            <label for="inputPassword" class="sr-only">Пароль</label>
            <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
            <div class="checkbox mb-3">
                <label>
                    <input type="checkbox" value="remember-me"> Запомнить меня
                </label>
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Войти</button>
            <button class="btn btn-lg btn-primary btn-block" type="register" href="../register.php">Зарегистрироваться</button>
            <p class="mt-5 mb-3 text-muted">Kirill Adamuk &copy; 2017-2018</p>
        </form>
    </div>
    <div class="container">
        <h1 class="mt-5">Sticky footer with fixed navbar</h1>
        <p class="lead">Pin a footer to the bottom of the viewport in desktop browsers with this custom HTML and CSS. A
            fixed navbar has been added with <code>padding-top: 60px;</code> on the <code>main &gt; .container</code>.
        </p>
        <p>Back to <a href="/docs/4.3/examples/sticky-footer/">the default sticky footer</a> minus the navbar.</p>
    </div>
</main>