<main role="main" class="flex-shrink-0">
    <div class="container">
        <form class="form-signin">
            <h1 class="h3 mb-3 font-weight-normal">Пожалуйста, войдите в свой аккаут</h1>
            <label for="inputEmail" class="sr-only">Адрес электронной почты</label>
            <input type="email" id="inputEmail" class="form-control" placeholder="Ваш e-mail" required autofocus>
            <label for="inputPassword" class="sr-only">Пароль</label>
            <input type="password" id="inputPassword" class="form-control" placeholder="Ваш пароль" required>
            <div class="checkbox mb-3">
                <label>
                    <input type="checkbox" value="remember-me"> Запомнить меня
                </label>
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Войти</button>
            <a class="btn btn-lg btn-block btn-lnk" role="button" href="register">Зарегистрироваться</a>
        </form>
    </div>
</main>