<div class="container content tournament">
    <div class="jumbotron">
        <h1 class="display-4">Турнир <?= htmlspecialchars($tournament->getName()); ?></h1>
        <p class="lead">Дата проведения: <?= $tournament->getDate(); ?></p>
        <hr class="my-4">
        <p>Текущий раунд: <?= $tournament->getCurrentRound(); ?></p>
        <p>Оценка количества раундов до конца турнира: <?= $tournament->getEstimation(); ?></p>
        <p class="lead">
            <a class="btn btn-secondary schedule" role="button">Скопировать ссылку на расписание турнира</a>
        </p>
    </div>

    <br>
    <?php if (isset($errors) && $errors): ?>
        <div class="alert alert-danger" role="alert">
            <?php foreach ($errors as $error): ?>
                <span class="error-messages"><?= $error; ?></span><br>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <form method="post" action="/tournament/show/<?= $tournament->getId() ?>/">
        <div>
            <input name="token_tournament" type="hidden"
                   value="<?= htmlspecialchars($_SESSION['token_tournament'], ENT_QUOTES); ?>">

            <?php if ($tournament->getStatus() == 'awaiting'): ?>
                <div class="btn-group container-fluid" role="group">
                    <button name='tournament_action' value='start' class="btn btn-success" type="submit">Начать
                        турнир
                    </button>
                    <button type="button" class="btn btn-secondary" onclick="window.location.href='/tournament/'">
                        Вернуться к перечню турниров
                    </button>
                </div>
                <table class="table table-striped">


                    <thead class="thead-light">
                    <tr>
                        <th scope="col">№</th>
                        <th scope="col">Ник</th>
                    </tr>
                    </thead>

                    <tbody>
                    <?php foreach ($tournament->getPlayers() as $number => $player): ?>
                        <tr>
                            <th scope="row"><?= $number + 1 ?></th>
                            <td><?= $player->getNickname(); ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            <?php endif; ?>

            <?php if ($tournament->getStatus() == 'in progress'): ?>
            <!--Кнопки управления-->
                <?php if ($is_owner): ?>
                    <div class="btn-group container-fluid" role="group">
                        <button name='tournament_action' value='next' type="submit" class="btn btn-success">Продолжить
                        </button>
                        <button name='tournament_action' value='send_home' type="submit" class="btn btn-info">Применить действия и повторить жеребьевку
                        </button>
                        <button id="tournament_reset" name='tournament_action' value='reset' type="submit" class="btn btn-danger">Сбросить
                            прогресс турнира
                        </button>
                    </div>
                <? endif; ?>
                <?php foreach ($tournament->getToss() as $pairOfTeams): ?>
                    <div class="row border m-3 p-0 no-gutters">
                        <?php foreach ($pairOfTeams as $k => $team): ?>
                            <div class="col row">
                                <div class="col ">
                                    <div id="team_card" class="card align-middle">
                                        <div class="card-header text-center"><h5>Команда <?= $team; ?></h5></div>
                                        <img src="https://dota2.ru/img/heroes/<?= (str_replace([' ', '-'], '_', strtolower($team))) ?>/portrait.jpg"
                                             class="card-img-top" alt="<?= $team ?>">
                                    </div>
                                </div>
                                <div class="col">
                                    <table class="table table-striped">

                                        <thead class="thead-light">
                                        <tr>
                                            <th scope="col">Ник</th>
                                            <th scope="col">Жизни</th>
                                            <?php if ($is_owner): ?>
                                                <th scope="col">Действия</th>
                                            <? endif; ?>
                                        </tr>
                                        </thead>

                                        <tbody>
                                        <?php foreach ($tournament->getPlayersByTeam($team) as $player): ?>
                                            <tr>
                                                <td><?= $player->getNickname(); ?></td>
                                                <td>
                                                    <span class="badge badge-pill badge-info"><?= $player->getLifes(); ?></span>
                                                </td>
                                                <?php if ($is_owner): ?>
                                                    <td>
                                                        <select name="sendHome[<?= $player->getId(); ?>]"
                                                                class="custom-select custom-select-sm mb-3">
                                                            <option disabled selected>Выбрать опции</option>
                                                            <option value="1">Cнять с посева</option>
                                                            <option value="2">Убрать жизнь и снять с посева</option>
                                                            <option value="3">Дисквалифицировать</option>
                                                        </select>
                                                    </td>
                                                <? endif; ?>
                                            </tr>
                                        <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <?php if ($is_owner && isset($pairOfTeams[$k + 1])): ?>
                                <div class="col">
                                    <select name="loosers[]" class="custom-select custom-select-lg mb-3">
                                        <option value="" disabled selected>Выбрать победителя</option>
                                        <?php foreach ($pairOfTeams as $t): ?>
                                            <option value="<?= $t ?>"><?= $t ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </div>
                <?php endforeach; ?>

                <!--Ожидающие-->
                <?php if ($tournament->getWaitingPlayers()): ?>
                    <div class="container-fluid">
                        <div>
                            <h5 class="text-center">Ожидающие</h5>
                            <table class="table table-striped">
                                <thead class="thead-light">
                                <tr>
                                    <th scope="col">Ник</th>
                                    <th scope="col">Жизни</th>
                                    <th scope="col">Отметка</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($tournament->getWaitingPlayers() as $player): ?>
                                    <tr>
                                        <td><?= $player->getNickname(); ?></td>
                                        <td>
                                            <span class="badge badge-pill badge-info"><?= $player->getLifes(); ?></span>
                                        </td>
                                        <td>
                                            <?php if($player->getIsSuspended()): ?>
                                            <span class="badge badge-pill badge-danger">Отстранен от раунда</span>
                                            <?php endif; ?>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                <?php endif; ?>

                <!--Выбывшие-->
                <?php if ($tournament->getLoosers()): ?>
                    <div class="container-fluid">
                        <div>
                            <h5 class="text-center">Выбывшие</h5>
                            <table class="table table-striped">
                                <thead class="thead-light">
                                <tr>
                                    <th scope="col">Ник</th>
                                    <th scope="col">Жизни</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($tournament->getLoosers() as $player): ?>
                                    <tr>
                                        <td><?= $player->getNickname(); ?></td>
                                        <td>
                                            <span class="badge badge-pill badge-info"><?= $player->getLifes(); ?></span>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                <?php endif; ?>
            <?php endif; ?>

            <?php if ($tournament->getStatus() == 'ended'): ?>
                <div class="btn-group container-fluid" role="group">
                    <button type="button" class="btn btn-secondary" onclick="window.location.href='/tournament/'">
                        Вернуться к перечню турниров
                    </button>
                    <button name='tournament_action' value='reset' type="submit" class="btn btn-danger">Сбросить
                        прогресс турнира
                    </button>
                </div>
                <table class="table table-striped">
                    <h4>Участники:</h4>
                    <br>
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">№</th>
                        <th scope="col">Ник</th>
                        <th scope="col">Жизни</th>
                        <?php if ($tournament->getPrizePool()): ?>
                        <th scope="col">Награда</th>
                        <?php endif; ?>
                    </tr>
                    </thead>

                    <tbody>
                    <?php foreach ($tournament->getPlayersOrderedByLifes() as $number => $player): ?>
                        <tr>
                            <th scope="row"><?= $number + 1 ?></th>
                            <td><?= $player->getNickname(); ?></td>
                            <td><?= $player->getLifes(); ?></td>
                            <?php if ($tournament->getPrizePool()): ?>
                                <td><?= $player->getPrize(); ?></td>
                            <?php endif; ?>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            <?php endif; ?>
        </div>

    </form>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.10/clipboard.min.js"></script>
<script>
    <?php require ROOT . '/js/tournament_show.js';?>
</script>
