<div class="container content tournament">

    <div class="container">
        <div class="row">
            <div class="col">
                <h1 class="text-center">Турнир <?= htmlspecialchars($tournament->getName()); ?></h1>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <h2 class=" text-center">Дата проведения: <?= $tournament->getDate(); ?></h2>

                <?php if ($tournament->getCurrentRound()): ?>
                    <h4 class=" text-center">Раунд №<?= $tournament->getCurrentRound(); ?></h4>
                <?php endif; ?>
            </div>
            <div class="col align-items-center justify-content-center">
                <div class="row">
                    <h4>Оценка количества раундов до конца турнира: <?= $tournament->getEstimation(); ?></h4>
                </div>
                <div class="row">
                    <button type="button" class="schedule btn btn-secondary"
                    ">
                    Скопировать ссылку на расписание турнира
                    </button>
                </div>
            </div>
        </div>
    </div>

    <br>
    <?php if (isset($errors) && $errors): ?>
        <div class="alert alert-danger" role="alert">
            <?php foreach ($errors as $error): ?>
                <span class="error-messages"><?= $error; ?></span><br>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <form method="post" action="/tournament/show/<?= $tournament->getId() ?>/">
        <div>
            <input name="token_tournament" type="hidden"
                   value="<?= htmlspecialchars($_SESSION['token_tournament'], ENT_QUOTES); ?>">

            <?php if ($tournament->getStatus() == 'awaiting'): ?>
                <table class="table table-striped">
                    <h4>Участники:</h4>
                    <br>
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">№</th>
                        <th scope="col">Ник</th>
                    </tr>
                    </thead>

                    <tbody>
                    <?php foreach ($tournament->getPlayers() as $number => $player): ?>
                        <tr>
                            <th scope="row"><?= $number + 1 ?></th>
                            <td><?= $player->getNickname(); ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                <div class="btn-group container-fluid" role="group">
                    <button name='tournament_action' value='start' class="btn btn-success" type="submit">Начать
                        турнир
                    </button>
                    <button type="button" class="btn btn-secondary" onclick="window.location.href='/tournament/'">
                        Вернуться к перечню турниров
                    </button>
                </div>
            <?php endif; ?>

            <?php if ($tournament->getStatus() == 'in progress'): ?>

                <?php foreach ($tournament->getToss() as $pairOfTeams): ?>
                    <div class="row border m-3 p-0 no-gutters">
                        <?php foreach ($pairOfTeams as $k => $team): ?>
                            <div class="col row">
                                <div class="col ">
                                    <div id="team_card" class="card align-middle">
                                        <div class="card-header text-center"><h5>Команда <?= $team; ?></h5></div>
                                        <img src="https://dota2.ru/img/heroes/<?= (str_replace([' ', '-'], '_', strtolower($team))) ?>/portrait.jpg"
                                             class="card-img-top" alt="<?= $team ?>">
                                    </div>
                                </div>
                                <div class="col">
                                    <table class="table table-striped">

                                        <thead class="thead-light">
                                        <tr>
                                            <th scope="col">Ник</th>
                                            <th scope="col">Жизни</th>
                                            <?php if($is_owner): ?>
                                                <th scope="col"></th>
                                            <? endif;?>
                                        </tr>
                                        </thead>

                                        <tbody>
                                        <?php foreach ($tournament->getPlayersByTeam($team) as $player): ?>
                                            <tr>
                                                <td><?= $player->getNickname(); ?></td>
                                                <td>
                                                    <span class="badge badge-pill badge-info"><?= $player->getLifes(); ?></span>
                                                </td>
                                                <?php if($is_owner): ?>
                                                <td>
                                                    <div class="btn-group" role="group">
                                                        <div class="custom-control custom-checkbox">
                                                            <input name="sendHome[]"
                                                                   value="<?= $player->getId(); ?>"
                                                                   type="checkbox"
                                                                   class="custom-control-input"
                                                                   id="customCheck<?= $player->getId(); ?>">
                                                            <label class="custom-control-label"
                                                                   for="customCheck<?= $player->getId(); ?>">Отправить
                                                                игрока
                                                                домой</label>
                                                        </div>
                                                    </div>
                                                </td>
                                                <? endif;?>
                                            </tr>
                                        <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <?php if ($is_owner && isset($pairOfTeams[$k + 1])): ?>
                            <div class="col">
                                <select name="loosers[]" class="custom-select custom-select-lg mb-3">
                                    <option value="" disabled selected>Выбрать победителя</option>
                                <?php foreach ($pairOfTeams as $t): ?>
                                    <option value="<?=$t?>"><?=$t?></option>
                                <?php endforeach; ?>
                                </select>
                            </div>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </div>
                <?php endforeach; ?>

                <!--Ожидающие-->
                <?php if ($tournament->getWaitingPlayers()): ?>
                    <div class="container-fluid">
                        <div>
                            <h5 class="text-center">Ожидающие</h5>
                            <table class="table table-striped">
                                <thead class="thead-light">
                                <tr>
                                    <th scope="col">Ник</th>
                                    <th scope="col">Жизни</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($tournament->getWaitingPlayers() as $player): ?>
                                    <tr>
                                        <td><?= $player->getNickname(); ?></td>
                                        <td>
                                            <span class="badge badge-pill badge-info"><?= $player->getLifes(); ?></span>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                <?php endif; ?>

                <!--Выбывшие-->
                <?php if ($tournament->getLoosers()): ?>
                    <div class="container-fluid">
                        <div>
                            <h5 class="text-center">Выбывшие</h5>
                            <table class="table table-striped">
                                <thead class="thead-light">
                                <tr>
                                    <th scope="col">Ник</th>
                                    <th scope="col">Жизни</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($tournament->getLoosers() as $player): ?>
                                    <tr>
                                        <td><?= $player->getNickname(); ?></td>
                                        <td>
                                            <span class="badge badge-pill badge-info"><?= $player->getLifes(); ?></span>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                <?php endif; ?>

                <?php if($is_owner): ?>
                    <div class="btn-group container-fluid" role="group">
                        <button name='tournament_action' value='next' type="submit" class="btn btn-success">Продолжить
                        </button>
                        <button name='tournament_action' value='send_home' type="submit" class="btn btn-info">Отправить
                            выбранных игроков домой
                        </button>
                        <button name='tournament_action' value='reset' type="submit" class="btn btn-danger">Сбросить
                            прогресс турнира
                        </button>
                    </div>
                <? endif;?>
            <?php endif; ?>

            <?php if ($tournament->getStatus() == 'ended'): ?>
                <table class="table table-striped">
                    <h4>Участники:</h4>
                    <br>
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">№</th>
                        <th scope="col">Ник</th>
                        <th scope="col">Жизни</th>
                    </tr>
                    </thead>

                    <tbody>
                    <?php foreach ($tournament->getPlayersOrderedByLifes() as $number => $player): ?>
                        <tr>
                            <th scope="row"><?= $number + 1 ?></th>
                            <td><?= $player->getNickname(); ?></td>
                            <td><?= $player->getLifes(); ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                <div class="btn-group container-fluid" role="group">
                    <button type="button" class="btn btn-secondary" onclick="window.location.href='/tournament/'">
                        Вернуться к перечню турниров
                    </button>
                    <button name='tournament_action' value='reset' type="submit" class="btn btn-danger">Сбросить
                        прогресс турнира
                    </button>
                </div>
            <?php endif; ?>
        </div>

    </form>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.10/clipboard.min.js"></script>
<script>
    <?php require ROOT . '/js/tournament_show.js';?>
</script>
