<div class="container content">
    <?php if (isset($notify) && ($notify == 'success')): ?>
        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">Турнир успешно создан!</h4>
        </div>
    <?php elseif (isset($notify) && ($notify == 'fail')): ?>
        <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading">Не удалось создать турнир</h4>
            <p>Пожалуйста, перезагрузите страницу и попробуйте снова.</p>
        </div>
    <?php endif; ?>
    <?php if (isset($tournaments) and $tournaments): ?>
        <h1 class="text-center">Список созданных турниров</h1>
        <br>
        <table class="table table-striped container-fluid">

            <thead class="thead-light">
            <tr>
                <th scope="col">№</th>
                <th scope="col">Наименование турнира</th>
                <th scope="col">Дата проведения турнира</th>
                <th scope="col">Действие</th>
            </tr>
            </thead>

            <tbody>

            <?php foreach ($tournaments as $number => $tournament): ?>
                <tr>
                    <th scope="row"><?= $number+1 ?></th>
                    <td><?= $tournament->getName() ?></td>
                    <td><?= $tournament->getDate() ?></td>
                    <td>
                        <form method="post" action="/tournament/">
                            <input name="token_tournament" type="hidden"
                                   value="<?= htmlspecialchars($_SESSION['token_tournament'], ENT_QUOTES); ?>">
                            <div class="btn-group" role="group">
                                <button type="button" class="btn btn-success" onclick="window.location.href='/tournament/show/<?=$tournament->getId()?>'">Перейти к турниру</button>
                                <button type="button" class="btn btn-info" onclick="window.location.href='/tournament/edit/<?=$tournament->getId()?>'">Редактировать данные игроков</button>
                                <button type="submit" class="btn btn-danger" name="delete" value="<?= $tournament->getId() ?>">Удалить турнир</button>
                            </div>
                        </form>
                    </td>
                </tr>

            <?php endforeach; ?>

            </tbody>
        </table>

    <?php endif; ?>
    <div>
        <a class="btn btn-lg btn-primary btn-block btn-lnk" role="button" href="/tournament/add">Добавить турнир</a>
    </div>
</div>