<div class="container content tournament">

    <h1 class=" text-center">Турнир <?= htmlspecialchars($tournament->getName()); ?></h1><br>

    <h2 class=" text-center">Дата проведения: <?= $tournament->getDatetime(); ?></h2>

    <?php if($tournament->getCurrentRound()):?>
    <h4 class=" text-center">Раунд №<?=$tournament->getCurrentRound(); ?></h4>
    <?php endif;?>

    <?php if($tournament->getRoundCount()):?>
        <h4 class=" text-center">Всего раундов <?=$tournament->getRoundCount(); ?></h4>
    <?php endif;?>

    <br>
    <form method="post" action="/tournament/show/<?= $tournament->getId() ?>/">
        <div>
            <input name="token_tournament" type="hidden"
                   value="<?= htmlspecialchars($_SESSION['token_tournament'], ENT_QUOTES); ?>">

            <?php if ($tournament->getStatus() == 'awaiting'): ?>
                <table class="table table-striped">
                    <h4>Участники:</h4>
                    <br>
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">№</th>
                        <th scope="col">Ник</th>
                    </tr>
                    </thead>

                    <tbody>
                    <?php foreach ($tournament->getPlayers() as $number => $player): ?>
                        <tr>
                            <th scope="row"><?= $number ?></th>
                            <td><?= $player->getNickname(); ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                <div class="btn-group container-fluid" role="group">
                    <button name='tournament_action' value='start' class="btn btn-success" type="submit">Начать
                        турнир
                    </button>
                    <button type="button" class="btn btn-secondary" onclick="window.location.href='/tournament/'">
                        Вернуться к перечню турниров
                    </button>
                </div>
            <?php endif; ?>

            <?php if ($tournament->getStatus() == 'in progress'): ?>

                <?php foreach ($toss as $pairOfTeams): ?>
                    <div class="row container border m-3 p-0">
                        <?php foreach ($pairOfTeams as $teamName => $team): ?>
                            <?php if($teamName != 'waiting'):?>
                            <div class="col row">
                                <div class="col">
                                    <div class="card">
                                        <img src="https://dota2.ru/img/heroes/<?= (str_replace([' ', '-'], '_', strtolower($teamName))) ?>/portrait.jpg"
                                             class="card-img-top" alt="<?= $teamName ?>">
                                        <div class="card-body">
                                            <h5 class="card-title text-center">Команда <?= $teamName; ?></h5>
                                            <div class="custom-control custom-switch">
                                                <input name="loosers[]" value="<?=$teamName;?>" type="checkbox" class="custom-control-input" id="customSwitch<?=$teamName;?>">
                                                <label class="custom-control-label" for="customSwitch<?=$teamName;?>">Проигравший</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col">
                                    <table class="table table-striped">

                                        <thead class="thead-light">
                                        <tr>
                                            <th scope="col">Ник</th>
                                            <th scope="col">Жизни</th>
                                            <th scope="col"></th>
                                        </tr>
                                        </thead>

                                        <tbody>
                                        <?php foreach ($team as $player): ?>
                                            <tr>
                                                <td><?= $player->getNickname(); ?></td>
                                                <td>
                                                    <span class="badge badge-pill badge-info"><?= $player->getLifes(); ?></span>
                                                </td>
                                                <td>
                                                    <div class="btn-group" role="group">
                                                        <div class="custom-control custom-checkbox">
                                                            <input name="sendHome[]"
                                                                   value="<?= $player->getId(); ?>"
                                                                   type="checkbox"
                                                                   class="custom-control-input"
                                                                   id="customCheck<?= $player->getId(); ?>">
                                                            <label class="custom-control-label"
                                                                   for="customCheck<?= $player->getId(); ?>">Отправить
                                                                игрока
                                                                домой</label>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        <?php else:?>
                                <div class="container-fluid">
                                    <div>
                                        <h5 class="text-center">Ожидающие</h5>
                                        <table class="table table-striped">
                                            <thead class="thead-light">
                                            <tr>
                                                <th scope="col">Ник</th>
                                                <th scope="col">Жизни</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <?php foreach ($team as $player): ?>
                                                <tr>
                                                    <td><?= $player->getNickname(); ?></td>
                                                    <td>
                                                        <span class="badge badge-pill badge-info"><?= $player->getLifes(); ?></span>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                        <?php endif;?>
                        <?php endforeach; ?>
                    </div>
                <?php endforeach; ?>

            <?php if($tournament->getLoosers()):?>
            <div class="container-fluid">
                <div>
                    <h5 class="text-center">Выбывшие</h5>
                    <table class="table table-striped">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col">Ник</th>
                            <th scope="col">Жизни</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($tournament->getLoosers() as $player): ?>
                            <tr>
                                <td><?= $player->getNickname(); ?></td>
                                <td>
                                    <span class="badge badge-pill badge-info"><?= $player->getLifes(); ?></span>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
            <?php endif;?>

                <div class="btn-group container-fluid" role="group">
                    <button name='tournament_action' value='next' type="submit" class="btn btn-success">Следующий
                        раунд
                    </button>
                    <button type="button" class="btn btn-info">Отправить выбранных игроков домой и провести повторную
                        жеребьевку раунда
                    </button>
                    <button type="button" class="btn btn-danger">Сбросить прогресс турнира</button>
                </div>
            <?php endif; ?>
        </div>

    </form>



</div>
