<?php


namespace App\models;


class TournamentInterregional extends Tournament  implements TournamentInterface
{
    public function __construct()
    {
        parent::__construct();
    }

    public function toss($teams)
    {
        return parent::toss($teams); // TODO: Change the autogenerated stub
    }

}